CREATE TABLE artistas {
    ID SERIAL PRIMARY KEY, 
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(20) NOT NULL,
    MEMBROS INT,
    GENERO_MUSICAL VARCHAR(50) NOT NULL,
    PAIS_ORIGEM VARCHAR(50),
    ANO_INICIO INT,
    MUSICA_MAIS_OUVIDA VARCHAR(50),
    ATIVO BOOLEAN DEFAULT TRUE
};